version: '3'

services:
    db:
        image: mariadb:latest
        container_name: mariadb
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
          - ./init:/docker-entrypoint-initdb.d
          - ./mariadb:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: Sentalf12!

    php:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
        - 8081:80
      depends_on:
        - db
      environment:
        PMA_HOST: db

    wordpress:
      image: wordpress
      container_name: wordpress
      restart: always
      ports:
        - 8080:80
      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: wp_user
        WORDPRESS_DB_PASSWORD: Sentalf12!
        WORDPRESS_DB_NAME: wordpress
      volumes:
        - ./wordpress:/var/www/html
      depends_on:
        - db

    testlink:
      image: 'docker.io/bitnami/testlink:latest'
      container_name: testlink
      ports:
        - '80:8080'
      environment:
        - TESTLINK_DATABASE_HOST=db
        - TESTLINK_DATABASE_PORT_NUMBER=3306
        - TESTLINK_DATABASE_USER=tl_user
        - TESTLINK_DATABASE_PASSWORD=Sentalf12!
        - TESTLINK_DATABASE_NAME=testlink
      volumes:
        - './testlink_data:/bitnami/testlink'
      depends_on:
        - db

    jira:
      depends_on:
        - db
      container_name: jira
      restart: always
      image: atlassian/jira-software:latest
      ports:
        - '8000:8080'
      volumes:
        - ./jira-data:/var/atlassian/jira  # JIRA_HOME